//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReGuilded.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReGuildedLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReGuildedLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReGuilded.Resources.ReGuildedLang", typeof(ReGuildedLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DownloadItem_Button {
            get {
                return ResourceManager.GetString("DownloadItem/Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string Downloads_Header {
            get {
                return ResourceManager.GetString("Downloads/Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        internal static string Downloads_InternalServerError {
            get {
                return ResourceManager.GetString("Downloads/InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string Downloads_Page_Title {
            get {
                return ResourceManager.GetString("Downloads/Page-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add additional content, change UI components or run any kind of code in Guilded..
        /// </summary>
        internal static string Index_Feature_Addons_Description {
            get {
                return ResourceManager.GetString("Index/Feature/Addons-Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        internal static string Index_Feature_Addons_Title {
            get {
                return ResourceManager.GetString("Index/Feature/Addons-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change or add sounds to your Guilded app..
        /// </summary>
        internal static string Index_Feature_Sound_Packs_Description {
            get {
                return ResourceManager.GetString("Index/Feature/Sound_Packs-Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Packs.
        /// </summary>
        internal static string Index_Feature_Sound_Packs_Title {
            get {
                return ResourceManager.GetString("Index/Feature/Sound_Packs-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the look of Guilded&apos;s UI using unrestricted CSS..
        /// </summary>
        internal static string Index_Feature_Themes_Description {
            get {
                return ResourceManager.GetString("Index/Feature/Themes-Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string Index_Feature_Themes_Title {
            get {
                return ResourceManager.GetString("Index/Feature/Themes-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Index_Page_Title {
            get {
                return ResourceManager.GetString("Index/Page-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter your Guilded client the way you want using ReGuilded..
        /// </summary>
        internal static string IndexLayout_Motto_Subtitle {
            get {
                return ResourceManager.GetString("IndexLayout/Motto/Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhance your experience.
        /// </summary>
        internal static string IndexLayout_Motto_Title {
            get {
                return ResourceManager.GetString("IndexLayout/Motto/Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download for {0}.
        /// </summary>
        internal static string IndexLayout_QuickDownload_DownloadForPlatform {
            get {
                return ResourceManager.GetString("IndexLayout/QuickDownload/DownloadForPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not using {0}? Click here.
        /// </summary>
        internal static string IndexLayout_QuickDownload_NotUsingPlatform {
            get {
                return ResourceManager.GetString("IndexLayout/QuickDownload/NotUsingPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the Credits..
        /// </summary>
        internal static string PageFooter_CreditLink {
            get {
                return ResourceManager.GetString("PageFooter/CreditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project wouldn&apos;t be possible without the amazing contributors along the way..
        /// </summary>
        internal static string PageFooter_CreditMessage {
            get {
                return ResourceManager.GetString("PageFooter/CreditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find us on:.
        /// </summary>
        internal static string PageFooter_FindUsOn {
            get {
                return ResourceManager.GetString("PageFooter/FindUsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string PageHeader_Downloads {
            get {
                return ResourceManager.GetString("PageHeader/Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhancements.
        /// </summary>
        internal static string PageHeader_Enhancements {
            get {
                return ResourceManager.GetString("PageHeader/Enhancements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        internal static string PageHeader_Enhancements_Addons {
            get {
                return ResourceManager.GetString("PageHeader/Enhancements/Addons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Packs.
        /// </summary>
        internal static string PageHeader_Enhancements_Sound_Packs {
            get {
                return ResourceManager.GetString("PageHeader/Enhancements/Sound_Packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        internal static string PageHeader_Enhancements_Themes {
            get {
                return ResourceManager.GetString("PageHeader/Enhancements/Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string PageHeader_Home {
            get {
                return ResourceManager.GetString("PageHeader/Home", resourceCulture);
            }
        }
    }
}
